Use .loc when you know the specific text labels or dates of your data. Use .iloc when you want to quickly grab data based on its physical location in the table (e.g., "get the first 5 rows and the last 2 columns")

In [3]:
import pandas as pd

data = {'Age': [25, 30, 35], 'City': ['New York', 'Paris', 'Tokyo']}
df = pd.DataFrame(data, index=['Alice', 'Bob', 'Charlie'])
df

         Age      City
Alice     25  New York
Bob       30     Paris
Charlie   35     Tokyo

In [2]:
df.loc['Alice']  # Returns the row for Alice

Age           25
City    New York
Name: Alice, dtype: object

In [4]:
df.iloc[0]       # Returns the 1st row (Alice), since it is at index 0

Age           25
City    New York
Name: Alice, dtype: object

In [5]:
df.loc['Alice':'Bob']  
# Returns BOTH Alice and Bob

       Age      City
Alice   25  New York
Bob     30     Paris

In [6]:
df.iloc[0:2]           
# Returns positions 0 and 1 (Alice and Bob). Position 2 is excluded

       Age      City
Alice   25  New York
Bob     30     Paris

In [7]:
df.loc['Bob', 'City']  # Returns 'Paris'

'Paris'

In [8]:
df.iloc[1, 1]          # Returns 'Paris' (2nd row, 2nd column)

'Paris'

In [9]:
df.loc[df['Age'] > 28]  # Returns rows for Bob and Charlie

         Age   City
Bob       30  Paris
Charlie   35  Tokyo